### ISSUE TITLE
Sphinx Control JS Issue

### ISSUE THREAD

**Issue by FriedrichMueller** [ChristopherStephan/IWGI-Speech#33]
Moin,

Derzeit verwende ich in der spinx_command.js folgenden code z.b.

if(hyp=="RIGHT"){

```
    stopRecording();
    startRecording();
    //document.getElementById("output").innerHTML = "";
    pan_right();
```

Dabei stope ich die recognition und starte sie neu. Würde ich das nicht tun würde der Befehl solange ausgeführt werden bis eine neue Hypothese (hyp) erkannt wird.

Eigentlich wollte ich die Sprachsteuerung per outputfield steuern- kann aber das Output field nicht bereinigen : dies ist die auskommentierte Zeile:

//document.getElementById("output").innerHTML = "";

Weis jemand wieso diese Zeile nicht funktioniert??

**Comment by schlomm** [comment]
Hi,
In general this should work, because the code-line 
<code>document.getElementById('output').innerHTML = "";</code>
deletes the **output**-div (I've tried it using the console).

For the moment I'm struggling with the order/usage of stop and startRecording();. Maybe we can have a skype meeting to solve my problems?!

Regards,
Dom

**Comment by FriedrichMueller** [comment]
Versuch einen Zeit Buffer einzubauen. Allerdings reagiert bei mir die Erkennung sehr sensibel. Ist das generell bei euch auch so?

**Comment by ChristopherStephan** [comment]
Ja, die Erkennung ist bei mir auch sehr sensibel. Sobald irgendein Signal ins Mikro geht, bekomme ich hier eine Hyp in der Console ausgegeben.

**Comment by schlomm** [comment]
Discarded.
We will concentrate on Googles Web Speech API
